# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "amdgpu"];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/22dab79b-621d-48d5-ab54-a0592cf2f75a";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=root" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/22dab79b-621d-48d5-ab54-a0592cf2f75a";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/22dab79b-621d-48d5-ab54-a0592cf2f75a";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=nix" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7571-F65E";
      fsType = "vfat";
    };

  fileSystems."/swap" =
    {
      device = "/dev/disk/by-uuid/22dab79b-621d-48d5-ab54-a0592cf2f75a";
      fsType = "btrfs";
      options = [ "noatime" "subvol=swap" ];
    };

  # fileSystems."/mnt/games" = {
  #   device = "/dev/disk/by-uuid/dab14479-8c57-4f41-aac0-4d78005dbedd";
  #   fsType = "btrfs";
  #   options = [ "compress=zstd" "noatime" "nosuid" "nodev" "nofail" "x-gvfs-show" ];
  #   label = "gamestorage";
  # };
  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/90bf654f-872d-469c-b4b0-f26699f1a1e2";
    fsType = "ext4";
    options = [ "noatime" "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    #Duplicate of device now label = "Games";
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/1a7661ed-6c37-4d6d-97dc-aae84f419742";
    fsType = "ext4";
    options = [ "noatime" "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    #label = "Storage";
  };





  swapDevices = [{ device = "/swap/swapfile"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
