#preload = /home/brian/.config/wallpaper/nix-purple.png
#preload = /home/brian/.config/wallpaper/flower.png
#preload = /home/brian/.config/wallpaper/shaded_landscape.png
#preload = /home/brian/.config/wallpaper/leaves.png
# preload = /home/brian/.config/wallpaper/matrix.png
#preload = /home/brian/.config/wallpaper/mountain-lake.png
#preload = /home/brian/.config/wallpaper/fantasy-world.png
preload = /home/brian/.config/wallpaper/leaves.png
preload = /home/brian/.config/wallpaper/retropc.jpg
preload = /home/brian/.config/wallpaper/sunset.jpg
preload = /home/brian/.config/wallpaper/colorful-painting.jpg
preload = /home/brian/.config/wallpaper/shaded_landscape.png
preload = /home/brian/.config/wallpaper/water-drop.jpg
#if more than one preload is desired then continue to preload other backgrounds
#preload = /path/to/next_image.png
# .. more preloads

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = ,/home/brian/.config/wallpaper/retropc.jpg
ipc = on
splash = false
