# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

 services.btrfs.autoScrub = {
      enable = true;
      interval = "weekly";
 };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/65a103fb-1937-4019-8579-2801fb396e15";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime"];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/b49bd4bf-77fa-46cf-88a5-6c7d00118346";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/65a103fb-1937-4019-8579-2801fb396e15";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/65a103fb-1937-4019-8579-2801fb396e15";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime"];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/65a103fb-1937-4019-8579-2801fb396e15";
      fsType = "btrfs";
      options = [ "subvol=swap"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/264A-C831";
      fsType = "vfat";
    };
  
  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
